version: "3.6"
services:
  frontend:
    image: ghcr.io/integratedproject-ii/front-end:main   
    ports: 
      - "80:80"  
networks:
    default:
        external:
            name: loykrathong_network
