version: "3.6"
services:
  front-end:
    image: ghcr.io/integratedproject-ii/front-end:dev     
    build: .
    dockerfile: ./Dockerfile

networks:
    default:
        external:
            name: loykrathong_network
