name: Front-end

on:
 push: 
  branches:
     - main 
 pull_request:
     branches: [ main ]
 
jobs: 
   build:
     runs-on: ubuntu-latest
     
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
      
     - name: Login to Github registry ghcr
       uses: docker/login-action@v1
       with:
         registry: ghcr.io
         username: ${{ github.repository_owner }}
         password: ${{ secrets.TOKEN_GITHUB_LOYKRATHONG }}
             
     - name: Create env file
       run: |
          echo VUE_APP_API=${{ secrets.VUE_APP_API }} >> .env
          
     - name: Build image and push Dockerfile
       uses: docker/build-push-action@v2
       with:
         file: ./Dockerfile
         push: true
         tags: ghcr.io/integratedproject-ii/front-end:main
   
     - name: Publish compose file
       uses: appleboy/scp-action@master
       with: 
         host: ${{ secrets.HOST }}
         username: ${{ secrets.SSH_USERNAME }}
         password: ${{ secrets.SSH_PASSWORD }}
         source: ./docker-compose.yml
         target: ./Docker-front-end
    
   deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
      
      - name: Deploy execute command ssh to remote server
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.SSH_USERNAME }}
         password: ${{ secrets.SSH_PASSWORD }}
         script: |
           docker-compose -f Docker-front-end/docker-compose.yml down 
           docker pull ghcr.io/integratedproject-ii/front-end:main 
           docker-compose -f Docker-front-end/docker-compose.yml up -d 
    
