name: Front-end

on:
 push: 
  branches:
     - main
     - dev  
 pull_request:
     branches: [ main ]
 
jobs: 
   build:
     runs-on: ubuntu-latest
     
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
      
     - name: Set env
       run: echo "ENV_NAME=$( [ "$GITHUB_REF" == "refs/heads/master" ] && echo 'dev' || echo ${GITHUB_REF##*/} )" >> $GITHUB_ENV
       
     - name: Login to Github registry ghcr
       uses: docker/login-action@v1
       with:
         registry: ghcr.io
         username: ${{ github.repository_owner }}
         password: ${{ secrets.TOKEN_GITHUB_LOYKRATHONG }}
         
     - name: Build image and push Dockerfile
       uses: docker/build-push-action@v2
       with:
         file: ./Dockerfile
         push: true
         tags: ghcr.io/integratedproject-ii/front-end:${{ env.ENV_NAME }}
   
     - name: Publish compose file
       uses: appleboy/scp-action@master
       with: 
         host: ${{ secrets.HOST }}
         username: ${{ secrets.SSH_USERNAME }}
         password: ${{ secrets.SSH_PASSWORD }}
         source: ./docker-compose.${{ env.ENV_NAME }}.yml
         target: ~/Docker-front-end
         
 deploy:
  push:
    branches:  
       - main
       - dev
  pull_request:
    branches:  main 

jobs:
  setup-node:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: set up node
      uses: actions/setup-node@master
      with:
        node-version: 14.15.4
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    
  build:
    needs: setup-node
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Set env
      run: echo "ENV_NAME=$( [ "$GITHUB_REF" == "refs/heads/master" ] && echo 'dev' || echo ${GITHUB_REF##*/} )" >> $GITHUB_ENV
    
    - name: Login to Github Docker Registry ghcr
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.TOKEN_GITHUB_LOYKRATHONG }}

    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile
        push: true
        tags: ghcr.io/integratedproject-ii/front-end:${{ env.ENV_NAME }} 
      
    - name: Publish compose file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./docker-compose.yml"
        target: "."
    
  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        
      - name: Set env
        run: echo "ENV_NAME=$( [ "$GITHUB_REF" == "refs/heads/master" ] && echo 'dev' || echo ${GITHUB_REF##*/} )" >> $GITHUB_ENV
      
      - name: Deploy execute command ssh to remote server
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.SSH_USERNAME }}
         password: ${{ secrets.SSH_PASSWORD }}
         script: |
             docker pull ghcr.io/integratedproject-ii/front-end:${{ env.ENV_NAME }}  
             docker-compose -f Docker-front-end/docker-compose.dev.yml down 
             docker-compose -f Docker-front-end/docker-compose.dev.yml up -d

    

