# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Front-end

on:
  push:
    branches:  main 
  pull_request:
    branches:  main 

jobs:
  setup-node:

    runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@master
    - name: set up node
      uses: actions/setup-node@master
      with:
        node-version: 14.15.4
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    
  build:
    needs: setup-node
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Set env
      run: echo "ENV_NAME=$( [ "$GITHUB_REF" == "refs/heads/master" ] && echo 'uat' || echo ${GITHUB_REF##*/} )" >> $GITHUB_ENV
    
    - name: Login to Github Docker Registry ghcr
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.TOKEN_GITHUB }}

    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile
        push: true
        tags: ghcr.io/pungpeee/IntegratedProject-II/Front-end:${{ env.ENV_NAME }} 
    
    
