name: Front-end

on:
  push:
    branches:  
       - main
       - dev
  pull_request:
    branches:  main 

jobs:
  setup-node:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: set up node
      uses: actions/setup-node@master
      with:
        node-version: 14.15.4
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    
  build:
    needs: setup-node
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Set env
      run: echo "ENV_NAME=$( [ "$GITHUB_REF" == "refs/heads/master" ] && echo 'dev' || echo ${GITHUB_REF##*/} )" >> $GITHUB_ENV
    
    - name: Login to Github Docker Registry ghcr
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.TOKEN_GITHUB_LOYKRATHONG }}

    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile
        push: true
        tags: ghcr.io/integratedproject-ii/front-end:${{ env.ENV_NAME }} 
    
  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set env
        run: echo "ENV_NAME=$( [ "$GITHUB_REF" == "refs/heads/master" ] && echo 'dev' || echo ${GITHUB_REF##*/} )" >> $GITHUB_ENV
      
      - name: Deploy execute command ssh to remote server
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         password: ${{ secrets.PASSWORD }}
         script: |
            docker pull ghcr.io/integratedproject-ii/front-end:${{ env.ENV_NAME }}  
            docker run -d --name Frontend -p 80:80 --network=loykrathong_network ghcr.io/integratedproject-ii/front-end:${{ env.ENV_NAME }} 
#          script: |
#             docker pull ghcr.io/pungpeee/front-end:${{ env.ENV_NAME }}   
#             docker-compose down 
#             docker-compose up -d

    
